name: "Deploy with heroku"

on:
  push:
    branches:
      - master
      - development
      - staging
      - uat
      - production

jobs:
  build:
    name: "deploy apps to heroku server"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "ci-cd-paymentmonitoring"
          heroku_email: "alpdizami94@gmail.com"
